<a class="logoBig" href="/">
    <figure class="logo j77-logo">
        <img src="<?= $this->EscapeHtmlAttr($this->basePath($this->srcBig)); ?>" alt="<?= $this->EscapeHtmlAttr($this->translate($this->alt)); ?>" title="<?= $this->EscapeHtmlAttr($this->translate($this->title)); ?>" />
    </figure>
</a>
<figure class="logoSmall">
    <img src="<?= $this->EscapeHtmlAttr($this->basePath($this->srcSmall)); ?>" alt="<?= $this->EscapeHtmlAttr($this->translate($this->alt)); ?>" title="<?= $this->EscapeHtmlAttr($this->translate($this->title)); ?>" />
</figure>
