<?= $this->doctype() ?>
<?= $this->htmlTag(['lang' => $this->locale()])->openTag() ?>
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(); ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?PHP 
            if($_COOKIE['darkmode'] ?? false)
                echo $this->headLink()->prependStylesheet($this->basePath('assets/election-main-dark.css'));
            else
                echo $this->headLink()->prependStylesheet($this->basePath('assets/election-main.css'));
        ?>

        <?PHP 
            echo $this->headScript()
                ->prependFile($this->basePath('assets/election-head.js'));
        ?>
</head>

<body class="election_layout_login" <?= ($_COOKIE['darkmode'] ?? false) ? 'data-bs-theme="dark"' : '' ; ?>>
    <?= $this->partial('layout/election/partials/header/index.phtml'); ?>
    <main>
        <?= $this->partial('layout/election/partials/aside/index.phtml'); ?>
        <div class="content">
            <div class="login-wrapper">
                <?= $this->election_login_page_left_content; ?>
                <div class="login--content">
                    <div class="login--heading">
                        <?= $this->election_login_form_header; ?>
                    </div>
                    <?= $this->content; ?>
                </div>
            </div>
            <?= $this->election_login_bottom; ?>
        </div>
    </main>
  
    <?= $this->inlineScript()->appendFile($this->basePath('assets/election-main.js')); ?>
</body>

</html>