<div class="container">
    <div class="row">
        <div class="col">
            <h1><?= $this->translate('Really delete this user?'); ?></h1>
            </div>
    </div>
    <p><?= $this->mustache($this->translate('You are about to delete the user with id "{{userId}}". Any relation to this user will be lost upon deletion.'), [
        'userId' => $this->item->getId(),
    ]); ?></p>
    <p class="text-end">
        <a class="btn btn-primary" href="<?= $this->url('admin-user-management/user/delete', ['id' => $this->item->getId()], ['query' => ['layout' => 'popup', 'forceDisableRedirect' => $this->forceDisableRedirect ? '1' : '0']]) ?>"><?= $this->translate('Delete') ?></a>
    </p>
</div>

